### ISSUE TITLE
Issue with the Cost computation mecanism

### ISSUE THREAD

**Issue by AkakiAkakievitch** [adammyhre/Unity-GOAP#1]
In GoapPlanner.cs, once you have found a path, the cheapestLeaf is selected as the leaf that has the lower cost.

```
if (FindPath(goalNode, agent.actions)) {
    // If the goalNode has no leaves and no action to perform try a different goal
    if (goalNode.IsLeafDead) continue;

    Stack<AgentAction> actionStack = new Stack<AgentAction>();

    //====== Here is the cheapestLeaf selection mecanism
    while (goalNode.Leaves.Count > 0) {
        var cheapestLeaf = goalNode.Leaves.OrderBy(leaf => leaf.Cost).First();
        goalNode = cheapestLeaf;
        actionStack.Push(cheapestLeaf.Action);
    }
    return new ActionPlan(goal, actionStack, goalNode.Cost);
}
```

Please consider the following example of a node tree
(You'll find the Action name associated to the node and the node cost in parenthesis)

```
 (0) 
-StoreStone (1) 
--CollectStone (2) 
---MoveToStoneSite (3) 
----GrabPickaxe (4) 
--BuyStone (2)
```

Given that tree and the cheapestLeaf selection mecanism seen before, the Planner selects the **bold** path (see below), which is obviously not the cheapest!

 **(0)
-StoreStone (1) 
--CollectStone (2) 
---MoveToStoneSite (3) 
----GrabPickaxe (4)**
--BuyStone (2)

Maybe there is a flaw in the cheapestLeaf selection and/or in the node cost computation.

I can think of two distinct ways of correcting the issue:
- process the whole tree to find the cheapestLeaf of all tree (and not the local cheapestLeaf) and then link back to the parents to construct the plan.

or

- Before the local cheapestLeaf selection mecanism, call a recusrive node method that will update the cost node as the max of the cost of its subtree nodes' cost...
Maybe something like:
```
public class Node {
    ...
    public float UpdateCostNode()
    {
        foreach(Node leaf in Leaves)
        {
            float tmpCost = leaf.UpdateCostNode();
            if (tmpCost > Cost)
                Cost = tmpCost;
        }
        return Cost;
    }
}
```

**Comment by adammyhre** [comment]
The search mechanism used in this repository is a basic DFS, as noted in the video. As pointed out in the code comments, you are welcome to implement a more sophisticated algorithm for calculating action chains if you like for your own project.

**Comment by AkakiAkakievitch** [comment]
Stupid me!
You said it on your video and you wrote it as a comment...
Sorry...
